name: Generate RSS Feed

on:
  push:
    paths:
      - "articles/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate RSS Feed
        run: |
          echo '<?xml version="1.0" encoding="UTF-8" ?>' > feed.xml
          echo '<rss version="2.0"><channel>' >> feed.xml
          echo '<title>TheVillageGist News Network</title>' >> feed.xml
          echo '<link>https://thevillagegist.com/</link>' >> feed.xml
          echo '<description>Latest Local and National News from Ewatto, Esan, and beyond.</description>' >> feed.xml
          echo '<language>en-us</language>' >> feed.xml

          for f in articles/*.html; do
            title=$(grep -m1 "title:" "$f" | cut -d':' -f2- | xargs)
            link=$(grep -m1 "link:" "$f" | cut -d':' -f2- | xargs)
            description=$(grep -m1 "description:" "$f" | cut -d':' -f2- | xargs)
            pubDate=$(grep -m1 "pubDate:" "$f" | cut -d':' -f2- | xargs)

            echo "<item>" >> feed.xml
            echo "<title>$title</title>" >> feed.xml
            echo "<link>$link</link>" >> feed.xml
            echo "<description>$description</description>" >> feed.xml
            echo "<pubDate>$pubDate</pubDate>" >> feed.xml
            echo "</item>" >> feed.xml
          done

          echo '</channel></rss>' >> feed.xml

      - name: Commit and push feed.xml
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add feed.xml
          git commit -m "Auto-update RSS feed"
          git push
